#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):
    s=" "+s
    for x in range(1,len(s)):
        if(ord(s[x])>=97 and ord(s[x])<=122 and s[x-1]==' '):
           s=s[:x]+chr(ord(s[x])-32)+s[x+1:]
    return s[1:]
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
